name: Inactive Test

on:
  workflow_dispatch:
    inputs:
      action_branch:
        description: The branch of the action to use
        default: main
        
      organization:
        description: The organization to process
        default: internal-test-organization
        
      activity_days:
        description: The number of days to use to analyze activity
        default: '30'
        
jobs:
  orgs:
    name: Analyze Organization
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Action
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.action_branch }}
        
      - name: Analyze organization
        id: analyze_org
        uses: ./
        with:
          token: ${{ secrets.OCTODEMO_TEMP_TOKEN }}
          organization: ${{ github.event.inputs.organization }}
          activity_days: ${{ github.event.inputs.activity_days }}

      - name: Results
        run: |
          echo "Inactive user list for last ${{ github.event.inputs.activity_days }} days"
          ${{ steps.analyze_org.outputs.report_json }}

        